BOT_TOKEN: "1677935498:AAFnSl2FXPaSZ8xlNAI2CzTGvaiQNBOj89Y"
MESSENGER_TOKEN: 'EAAF5ZA8L6hnUBAE9hZCq5LcMajjvZBQsnDjeEd7iXBDfNfJk408XW6HiZB2lytZChemgP7wpr5UYd1t3gz47MnEhy6bJfsZCjmIUQU9khQLMZCUwIMZCzFZCCiRbLi2ImVKlrwleRpAcSbSNmjWZAgp27KuvoLVXpDrFC2ujpdZAWtauRpZAozhAhDen'
MESSENGER_TEST_TOKEN: <<token>>
MESSENGER_VERIFY_TOKEN: 'bonobo'